In [6]:
import pandas as pd

In [7]:

fruits = pd.DataFrame({'Apples' : [30], 'Bananas' : [21]})
fruits

   Apples  Bananas
0      30       21

In [10]:
fruits['Apples']

0    30
Name: Apples, dtype: int64

In [9]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], index = ['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Dinner')

In [11]:
import pandas as pd

data = {
    'Name': ['Tom', 'Jerry', 'Spike', 'Tyke'],
    'Age': [20, 21, 19, 18],
    'City': ['NY', 'LA', 'TX', 'SF']
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print(df)

    Name  Age City
a    Tom   20   NY
b  Jerry   21   LA
c  Spike   19   TX
d   Tyke   18   SF

In [17]:
df.loc['a':'c']

    Name  Age City
a    Tom   20   NY
b  Jerry   21   LA
c  Spike   19   TX

In [18]:

import pandas as pd

df = pd.DataFrame({
    'country': ['Italy', 'Portugal', 'US', 'US'],
    'province': ['Sicily & Sardinia', 'Douro', 'California', 'New York'],
    'region_1': ['Etna', None, 'Napa Valley', 'Finger Lakes'],
    'region_2': [None, None, 'Napa', 'Finger Lakes']
}, index=[0, 1, 10, 100])

print(df)

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes